spring:

  # Live Reload
  devtools:
    livereload:
      enabled: true

  # Mustache Cache
  mustache:
    cache:
      false

  # H2 Repository Location
  datasource:
    url: jdbc:h2:~/data/bookclub

  # Spring Jpa ddl
  jpa:
    hibernate:
      ddl-auto: update

  #Spring Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: melon975123@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true

jwt:
  secret: "12345678901234567890123456789010"

interpark:
  apikey: 0556AC2C10B20DE12D9542F0F297FA49B77E4C80832EFAC91AFB16C6555384CC
