server:
  port: 9059
  servlet:
    session:
      timeout: 180s

spring:
  profiles: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  datasource:
#    url: jdbc:h2:file:~/dev/temp/h2db/bookclub
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  datasource:
    hikari:
      write:
        url: jdbc:mysql://34.125.215.241:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
        jdbc-url: jdbc:mysql://34.125.215.241:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: bookroot
        password: 1234

      read:
        url: jdbc:mysql://34.125.215.241:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
          jdbc-url: jdbc:mysql://34.125.215.241:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: bookroot
          password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://34.85.16.173:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
#    jdbc-url: jdbc:mysql://34.85.16.173:3306/bookclub?serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update

    # Query show
    show-sql: true

    # Query pretty print
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

    elasticsearch:
      hosts: 34.64.112.123,34.64.228.237,34.64.109.20,34.64.114.178
      port: 9200

  rabbitmq:
    host: 34.84.34.164
    username: guest
    password: guest
    port: 5672

  main:
    allow-bean-definition-overriding: true

  mail:
    username: ENC(/qNjHfAouomFQW84ddaVlwSyuuBwMnqvIQdsY5EHeCs=)
    password: ENC(OpCG3YawFvaXQBrIQydUzIifc6qiCuqm2UiholPJfYY=)
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

cloud:
  aws:
    credentials:
      accessKey: ENC(t85euNlMYc+msQ4pEKHLzk5YCX9YLHJw8N4mkJikTxM=)
      secretKey: ENC(ikC4S1IPrVoyLKo+qj2NbqeIrUvuU9uDVZnuvcAZ5mI49RyimDFVcYM/9pq6bTnqI6X2FQTgm/Q=)
    region:
      static: ENC(L/MEm2i3lEQDO2T9uUqbsaSghj4x/B8j)
    s3:
      bucket: ENC(hvQDB7YyZ6K1iDilh2Q0916cVdvwphrtphgowzmOSfo=)

jwt:
  secret: ENC(rNVZq1LVNtYJdp77CTD6odf0ycDO1NaT3wUzM54cdFoFytdo+30M4m3zV8kvCT/P)

interpark:
  apikey: ENC(csr4tYBLs+JB0ufHJ7jJuR55ekmN/HyY02kvOtnGHTOORTPKARjLUuqjVX28W8szbsPy43k5qeikNA4Ud/1yczTxrBOOkMS8xgtKtD3as8Y=)

resources:
  uri_path: /upload
  location: /opt/upload/

image:
  path: ENC(lY4tnO32eKTp0P0ExJaHeQFAU+6tfUq7nsBdtWOUHkMICPMky+JIQZ6wmpxhzfDa)

logging:
  config: classpath:log4j2.xml
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
          descriptor:
            sql: trace

jasypt:
  key: ENC(Ma5/uTJf8gChwHgjSmo9HemMwEJfQqxq)
  encryptor:
    bean: jasyptStringEncryptor

sentry:
  dsn: ENC(2JTLuAB3yghUCxXLi4ii2ApDUeDt+hQ9HmL9EEoVcBO5zmFbx6cYG8AAH4161uWuSHBeG0Bace1GbawyNTEwUo+RTn7NCv7ktATlEzUOzDr+dMnXjdDNug==)