server:
  port: 9059
  servlet:
    session:
      timeout: 30s

spring:
  profiles: prod

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: ENC(PlSoR8yb+rdbXX712zEbpxHkDt0x4X9zjM6wHkViyMMQpipIYjZFoBTfi7oouRK7QWDho6zRBUM=)
    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
#    url: ENC(UhF92Os3ZVe+9Hm1mNENnweWRmgkrty/iWcSyQRVm4liJErpfHK9v594PY687n1skaJ+u3wvUQ0bGVgt89/nomAipcB+KGl0wD/8kbC0wG5NjspEzb8TbmIjeNULueUCmcN20iW/mks=)
#    jdbc-url: ENC(22yXNiZ07pEukQbWeBl++wue0+RVk8PitR0RJ9oqVdMI7X7DBwDJVW8QOYeOLzDc0KUzHotgn0dvlvjtrD+TAkxE5jy4hpHNy3Qu4vbF1u4MdFwxtTQEtyr6H/nmf1EVW+IIglq47Qt5enr6yyliDBMuhnR+pGcT0qJgpd9zDiM=)
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ENC(zuNFykPTMKRsOAwjahsIcg==)
#    password: ENC(2JWfpVnJYUhB01mCISW3s8RPUNktgC3q)
  url: jdbc:postgresql://34.85.16.173:5432/bookclub
  driverClassName: org.postgresql.Driver
  username: admin
  password: admin

  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

    # Query show
    show-sql: true

    # Query pretty print
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

    elasticsearch:
      hosts: 10.178.0.2,10.178.0.3,10.178.0.4,10.178.0.5
      port: 9200

  rabbitmq:
    host: 34.84.34.164
    username: guest
    password: guest
    port: 5672

  mail:
    username: ENC(/qNjHfAouomFQW84ddaVlwSyuuBwMnqvIQdsY5EHeCs=)
    password: ENC(108QkIuAdhSx2x4QIBI8A9GuNVwmxSh7)
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

cloud:
  aws:
    credentials:
      accessKey: ENC(t85euNlMYc+msQ4pEKHLzk5YCX9YLHJw8N4mkJikTxM=)
      secretKey: ENC(ikC4S1IPrVoyLKo+qj2NbqeIrUvuU9uDVZnuvcAZ5mI49RyimDFVcYM/9pq6bTnqI6X2FQTgm/Q=)
    region:
      static: ENC(L/MEm2i3lEQDO2T9uUqbsaSghj4x/B8j)
    s3:
      bucket: ENC(hvQDB7YyZ6K1iDilh2Q0916cVdvwphrtphgowzmOSfo=)

jwt:
  secret: ENC(rNVZq1LVNtYJdp77CTD6odf0ycDO1NaT3wUzM54cdFoFytdo+30M4m3zV8kvCT/P)

interpark:
  apikey: ENC(csr4tYBLs+JB0ufHJ7jJuR55ekmN/HyY02kvOtnGHTOORTPKARjLUuqjVX28W8szbsPy43k5qeikNA4Ud/1yczTxrBOOkMS8xgtKtD3as8Y=)

resources:
  uri_path: /upload
  location: /opt/upload/

image:
  path: ENC(lY4tnO32eKTp0P0ExJaHeQFAU+6tfUq7nsBdtWOUHkMICPMky+JIQZ6wmpxhzfDa)

logging:
  config: classpath:log4j2.xml

jasypt:
  key: ENC(Ma5/uTJf8gChwHgjSmo9HemMwEJfQqxq)
  encryptor:
    bean: jasyptStringEncryptor