spring:
  profiles:
    active: dev

  datasource:
    hikari:
      read:
        #url: jdbc:h2:tcp://localhost/~/bookclub
        jdbc-url: jdbc:h2:tcp://localhost/~/bookclub
        driver-class-name: org.h2.Driver
        username: sa
        password:

      write:
        #url: jdbc:h2:tcp://localhost/~/jdbc
        jdbc-url: jdbc:h2:tcp://localhost/~/bookclub
        driver-class-name: org.h2.Driver
        username: sa
        password: